Vagrant.configure("2") do |config|
  # Linux distribuce (Ubuntu 22.04 LTS)
  config.vm.box = "ubuntu/jammy64"

  # Název virtuálního stroje
  config.vm.hostname = "webserver"

  # Port forwarding z hostitele (8080) na VM (80)
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true

  # Přidání tvého veřejného SSH klíče
  config.vm.provision "shell", inline: <<-SHELL
    echo ">>> Přidávám SSH klíč..."
    mkdir -p /home/vagrant/.ssh
    cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SHELL

  # Instalace Apache pomocí externího skriptu
  config.vm.provision "shell", path: "install_apache.sh"
end